"""Hotfix values for the services-template BlueAPI chart."""

from __future__ import annotations

import shlex
from pathlib import Path
from typing import Any

from .hotfix_core import HotfixError
from .hotfix_values import claim_for
from .launcher import target_container_name, target_uid_gid
from .lifecycle_supervisor import runtime_mounts, runtime_volumes, supervisor
from .model import HOTFIX_APP_PATH, HOTFIX_CLAIM_VOLUME

WRAPPER_NAME = "podbench-wrapper"
WRAPPER_PATH = "/app/.venv/bin/blueapi"


def _liveness_probe() -> list[str]:
    """A liveness probe that passes while the application is held.

    Only liveness is replaced. Startup and readiness stay the chart's httpGet
    probes: the supervisor starts without a hold, and readiness should fail
    while the application is held. The service therefore owns startup
    headroom in its own values, which regeneration does not overwrite.
    """
    return [
        "exec:",
        "  command:",
        "    - bash",
        "    - -c",
        "    - >-",
        "      [ -e /tmp/podbench-hold ] || exec /app/.venv/bin/python -c",
        "      'import urllib.request;",
        '      urllib.request.urlopen("http://127.0.0.1:8000/healthz", timeout=1)\'',
    ]


def workload(
    pod: dict[str, Any], app: str, container: str | None, gid: int | None
) -> list[str]:
    chosen = target_container_name(pod, container or "blueapi")
    _, discovered_gid = target_uid_gid(pod, chosen)
    gid = gid if gid is not None else discovered_gid
    if gid is None:
        raise HotfixError("the target gid is not reported; pass --gid")
    lines = [
        "debug:",
        "  enabled: false",
        "podSecurityContext:",
        f"  fsGroup: {gid}",
        "volumes:",
        f"  - name: {HOTFIX_CLAIM_VOLUME}",
        "    persistentVolumeClaim:",
        f"      claimName: {claim_for(app)}",
        *runtime_volumes(app),
        f"  - name: {WRAPPER_NAME}",
        "    configMap:",
        f"      name: {app}-{WRAPPER_NAME}",
        "      defaultMode: 0755",
        "volumeMounts:",
        f"  - name: {HOTFIX_CLAIM_VOLUME}",
        f"    mountPath: {HOTFIX_APP_PATH}",
        *runtime_mounts(),
        f"  - name: {WRAPPER_NAME}",
        f"    mountPath: {WRAPPER_PATH}",
        "    subPath: blueapi",
        "livenessProbe:",
        "  httpGet: null",
        *[f"  {line}" for line in _liveness_probe()],
    ]
    return lines


def write_template(service: Path) -> tuple[Path, bool]:
    path = service / "templates" / "podbench-wrapper.yaml"
    startup = "podbench_python /app/.venv/bin/python -m blueapi "
    health = (
        "/app/.venv/bin/python -c 'import urllib.request; "
        'urllib.request.urlopen("http://127.0.0.1:8000/healthz", timeout=1)' + "'"
    )
    script = 'printf -v args "%q " "$@"\n'
    script += supervisor(shlex.quote(startup) + '"$args"', health=health)
    content = (
        "# Generated by podbench hotfix enable.\n"
        "apiVersion: v1\nkind: ConfigMap\nmetadata:\n"
        "  name: {{ .Release.Name }}-podbench-wrapper\ndata:\n  blueapi: |\n"
        "    #!/bin/bash\n" + "".join(f"    {line}\n" for line in script.splitlines())
    )
    if path.exists() and path.read_text() == content:
        return path, False
    path.parent.mkdir(exist_ok=True)
    path.write_text(content)
    return path, True
