"""Hotfix values for the services-template BlueAPI chart."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .hotfix_core import HotfixError
from .hotfix_values import claim_for
from .launcher import target_container_name, target_uid_gid
from .model import HOTFIX_APP_PATH, HOTFIX_CLAIM_VOLUME

WRAPPER_NAME = "podbench-wrapper"
WRAPPER_PATH = "/app/.venv/bin/blueapi"


def workload(
    pod: dict[str, Any], app: str, container: str | None, gid: int | None
) -> list[str]:
    chosen = target_container_name(pod, container)
    _, discovered_gid = target_uid_gid(pod, chosen)
    gid = gid if gid is not None else discovered_gid
    if gid is None:
        raise HotfixError("the target gid is not reported; pass --gid")
    probe = [
        "exec:",
        "  command:",
        "    - bash",
        "    - -c",
        "    - >-",
        "      [ -e /tmp/podbench-hold ] || exec /app/.venv/bin/python -c",
        "      'import urllib.request;",
        '      urllib.request.urlopen("http://127.0.0.1:8000/healthz", timeout=1)\'',
    ]
    lines = [
        "debug:",
        "  enabled: false",
        "podSecurityContext:",
        f"  fsGroup: {gid}",
        "volumes:",
        f"  - name: {HOTFIX_CLAIM_VOLUME}",
        "    persistentVolumeClaim:",
        f"      claimName: {claim_for(app)}",
        f"  - name: {WRAPPER_NAME}",
        "    configMap:",
        f"      name: {app}-{WRAPPER_NAME}",
        "      defaultMode: 0755",
        "volumeMounts:",
        f"  - name: {HOTFIX_CLAIM_VOLUME}",
        f"    mountPath: {HOTFIX_APP_PATH}",
        f"  - name: {WRAPPER_NAME}",
        f"    mountPath: {WRAPPER_PATH}",
        "    subPath: blueapi",
        "livenessProbe:",
        "  httpGet: null",
        *[f"  {line}" for line in probe],
        "readinessProbe:",
        "  httpGet: null",
        *[f"  {line}" for line in probe],
        "startupProbe:",
        "  httpGet: null",
        *[f"  {line}" for line in probe],
    ]
    return lines


def write_template(service: Path) -> tuple[Path, bool]:
    path = service / "templates" / "podbench-wrapper.yaml"
    content = """# Generated by podbench hotfix enable.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-podbench-wrapper
data:
  blueapi: |
    #!/bin/bash
    while :; do
      if [ -f /podbench/app/.podbench-ptrace.so ]; then
        export LD_PRELOAD=/podbench/app/.podbench-ptrace.so
      fi
      if [ -x /podbench/app/.venv/bin/python ]; then
        python=/podbench/app/.venv/bin/python
      else
        python=/app/.venv/bin/python
      fi
      setsid "$python" -m blueapi "$@" &
      child=$!
      echo $child > /tmp/podbench-child.pid
      wait $child; rc=$?
      kill -TERM -"$child" 2>/dev/null || true
      [ -e /tmp/podbench-hold ] || exit $rc
    done
"""
    if path.exists() and path.read_text() == content:
        return path, False
    path.parent.mkdir(exist_ok=True)
    path.write_text(content)
    return path, True
